### ISSUE TITLE
Database Connection Error

### ISSUE THREAD

**Issue by nomadturk** [ygvn/IPv6-Subnet-Calculator-Tool-CSharp#2]
I've been trying to make a database connection but it seem I've encountered an error.

MySQL Connector Used: ODBC 5.3.11
Program Version: 3.8 and 3.9

I have created an empty mysql database since there was no template provided and added a table name for it to create one.

![image](https://user-images.githubusercontent.com/10355660/49687099-28a84e00-fb0f-11e8-919b-5d93f26e6bac.png)

And it throws out a table doesn't exist error using the database name.

![image](https://user-images.githubusercontent.com/10355660/49687097-16c6ab00-fb0f-11e8-8af8-db0596e35ff6.png)

But when I set the table name to be the same with database name, it connected without a problem though. This is kinda weird behavior.

But when I check the database, I see that the other names I tried were already created on the server as well:

![image](https://user-images.githubusercontent.com/10355660/49687339-a752ba80-fb12-11e8-99c0-b877c96fe4ac.png)

Also, I think it would've been better if program were to remember the DB settings and the prefix when you reopen it.

**Comment by ygvn** [comment]
Root Cause =>  Source File: Form1.cs, Line Number: 2211
The table name was not in 'MySQL Qualified Name' format, and there were only dbname.
If the tablename is not in 'qualified name', then MySQL Server uses 'admin_ipv6'.'admin_ipv6'
which is incorrect.
All tablename variables were put into MySQL Qualified Name format, i.e. 'dbname'.'tablename'
and error cleared.
Version v3.9.1 released.

Thanks for the feedback.

**Comment by nomadturk** [comment]
Cool, that was way too fast. 
Thank you for the software.

Guess for the last sentence, I should open a new issue. :)

**Comment by ygvn** [comment]
> Cool, that was way too fast.
> Thank you for the software.
> 
> Guess for the last sentence, I should open a new issue. :)

Due to security reasons, this application intended not to create any file or folder on your computer,
not to modify any entry from your Windows registry library, and not to remember user settings.

Thank you for your comments.
